sudo: required
language: ruby
services:
  - docker
before_install:
  - bin/setup
  - gem install -v 2.2 bundler -N
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - rake
