version: '3'
services:
  spec:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/simple_jsonapi_client
  console:
    build: .
    command: bin/development_start
    volumes:
      - .:/simple_jsonapi_client
