version: '3'
services:
  db:
    image: postgres
  jsonapi_app:
    build: ./spec/jsonapi_app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./spec/jsonapi_app:/jsonapi_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  spec:
    build: .
    command: bundle exec rspec
    volumes:
      - .:/simple_jsonapi_client
    depends_on:
      - jsonapi_app
  console:
    build: .
    command: bin/development_start
    volumes:
      - .:/simple_jsonapi_client
    depends_on:
      - jsonapi_app
